### ISSUE TITLE
score over the whole topics

### ISSUE THREAD

**Issue by un-lock-me** [jhlau/topic-coherence-sensitivity#1]
Thanks for sharing the code. I tried this code, however I got one question left. why you reported the coherence score per topic?
Usually in the papers they report the score over all the topics. for example if we run a topic modeling on the 20 newsgroup data set, and we set number of topic 20, then we report only one coherence score related to all the topics.

can you please share your idea how can I achieve that score. Is only averaging all the coherence per topics makes sense?

Thanks

**Comment by jhlau** [comment]
It depends on what you want to do. If you want to compare topic models, you'd aggregate the score (e.g. by taking mean). But if you want to filter out bad topics, you'd want to look at the individual coherence score for each topic.
