### ISSUE TITLE
sharing the preprocessed link

### ISSUE THREAD

**Issue by benam2** [jhlau/topic-coherence-sensitivity#2]
Hello,

Actually the link shared in the read me does not work any more.

Could you please share the link with me?

**Comment by jhlau** [comment]
Link updated and should be working now.

**Comment by benam2** [comment]
I appreciate it. I have one more question here. 

If I want to calculate coherence score over the reuters data set, Is it okay to use both wiki and news as the source for computing co-occurances?

Thank you very much:)

**Comment by jhlau** [comment]
Sure. I don't see why not.

**Comment by benam2** [comment]
And the last question. Is the news corpus here is exactly `20news group data set`? or it is another news data set?

Thanks :)
