### ISSUE TITLE
raises error

### ISSUE THREAD

**Issue by benam2** [jhlau/topic-coherence-sensitivity#3]
Again thank you for your help,
Could you please help me with this error:
I decided to have three configuration(10, 15, 20).

```
Computing NPMI for top-N = 10...
Traceback (most recent call last):
  File "ComputeObservedCoherence.py", line 151, in <module>
    c = calc_topic_coherence(topic_list)
  File "ComputeObservedCoherence.py", line 111, in calc_topic_coherence
    return float(sum(topic_assoc))/len(topic_assoc)
ZeroDivisionError: float division by zero
```

**Comment by benam2** [comment]
I just added 1 to `len(topic_assoc)` and it fixed but im not sure it is a valid thing to do.

once I added 1 to it it gives me the output, however, this three measure has been repeated for all the topics.
```
        Top 10 coherence score = -0.978260869565
	Top 15 coherence score = -0.990566037736
	Top 20 coherence score = -0.994764397906
```

Could you please share your view regarding this with me?

This is the preprocessing step I took: tokenize, lower case, remove stop words, stemmed.

**Comment by benam2** [comment]
Could you please help me with this as well?

**Comment by un-lock-me** [comment]
I looked at my files and found there was empty line in between so that was the reason for the error. However, I am not still getting what is wrong that I get all negative score. Could you please share your idea about this with me?
